import Navbar from "@/components/Navbar";
import { AuthContextProvider } from "@/helpers/auth-context";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500","600", "700"],
  variable: '--font-poppins'
});

export const metadata = {
  title: "Stokvel",
  description: "Generated by Mandla Mbolekwa",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body>
        <AuthContextProvider>
          <Navbar />
          <Toaster />
          <div>{children}</div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
