import Navbar from "@/components/Navbar";
import { AuthContextProvider } from "@/helpers/auth-context";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Stokvel",
  description: "Generated by Mandla Mbolekwa",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <Navbar />
          <div>{children}</div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
